### ISSUE TITLE
Tooling dependencies for the Getting Started (go-filecoin) guide

### ISSUE THREAD

**Issue by dennis-tra** [filecoin-project/venus-docs#31]
Hi there,

I just spun up a fresh Ubuntu-VM on GCP and tried to follow along the [Getting Started](https://go.filecoin.io/go-filecoin-tutorial/Getting-Started.html)  guide and noticed that I needed to install the following additional tools:

```shell
sudo apt install golang-go # that's mentioned in the guide
sudo apt install jq
sudo apt install ocl-icd-opencl-dev
```

Not sure about the latter one, but the build command failed due to an OpenCL issue. Just wanted to leave this here in case you want to add it to the guide ✌️

**Comment by Fatman13** [comment]
Thank you for catching that! 

Will do. Feel free to create a pr at same time.
